quotes = [
  ["This is why we need a", "men's rights movement,", "to counteract this BS."],
  ["If nobody else is going to", "stand up to feminists,", "who will?"],
  ["But what about the men?", "", ""],
  ["You can't cut back on our", "first amendment rights!", "you'll regret this!"],
  ["I do not fear getting", "banned from here.", "I consider it a blessing."],     
  ["I know you think of", "yourselves as trolls", "but you're not."],
  ["What a psuedo-", "intellectual shithole", "this place is."],
  ["I'm not some fat beardmad", "neckbeard either. I can", "bench almost 315 pounds."],
  ["This sub should be banned", "You people are why we", "can't have nice things."],
  ["If you don't like it,", "get off the Internet.", ""],
  ["I mean, I'm not even mad,", "I just pity you guys.", ""],
  ["For too long we have", "sat back and watched you", "shrill harpies propagate."],
  ["Fuck off back to the", "hug box that is Tumblr.", "leave our site alone."],
  ["Whenever I visit this", "subreddit I'm left hating", "myself for having a penis."],
  ["This place is a cesspool", "of unnecessary anger", "and self pity."],
  ["Do you think you're", "shocking someone with", "your phallic emoticons?"],
  ["The vast majority of the", "things submitted to this", "sub are harmless jokes."],
  ["I won't inundate you with", "spam, though I very", "easily could."],
  ["I'm just being a human", "instead of trying to", "seem morally superior."],
  ["All you do is disrupt", "this unity and make", "people uncomfortable."],
  ["If there's anything Reddit", "admins love, it's helping", "kill free speech."],
  ["Downvote all you want,", "Shitlords will unleash a", "torrent of hatred."],
  ["Honestly I tell my", "girlfriend to make me", "a sammich all the time."],
  ["You're corrupting", "everything Reddit stands", "for."],
  ["If the world was up to", "you we'd live in some", "misandrist dictatorship."],
  ["I will take action against", "this sub for violating", "multiple federal laws."],
  ["Actually, it's about", "ethics in video game", "journalism!"],
  ["Keep sending those", "emails!", ""],
  ["It started with jailbait,", "but I wasn't ephebophile", "so I didn't speak up."],
  ["It's all about the SJW", "feminist hugbox", "offenditron narrative."],
  ["I feel like I am in a", "virtual north korea right", "now."],
  ["Gamergate has stopped", "Social Justice like a", "titanium wall."],
  ["Have you ever considered", "that some of us love", "using slurs?"],
  ["ISIS is objectively less", "violent than internet", "feminists."],
  ["SJWs are the nazis of our", "time. They'd holocaust", "every white male."],
  ["You go around calling", "everyone racist when you", "are in fact the racists."],
  ["SRS meets most of the", "criteria needed for being", "an internet cult."],
  ["The Cabal acts as their", "cool kids club they were", "not good enough for IRL."],
  ["Powerful forces against", "us. All we have is being", "right and smarter people."],
  ["It is impossible for a", "SJW to not do anything", "wrong."],
  ["Isn't deleting internet", "comments analogous to", "burning books?"],
  ["We have the SJWS on the", "run but we cannot stop", "now."],
  ["CIS is a way for", "extremists to label", "people they hate."],
  ["Feminism dies right here,", "right now. Gamergate is", "the first to stand up."],
  ["Biggest problem facing", "the world today?", "Internet moderation."],
  ["Moderate feminist is like", "saying you're a moderate", "KKK grand wizard."],
  ["All feminists are", "censorship loving", "psychos."],
  ["Don't wanna sound racist,", "the whole 'civil rights'", "thing was bullshit too."],
  ["Sucks that we can't whip", "out the LOIC and nuke", "these fuckers."],
  ["This is good for Bitcoin.", "", ""],
  ["I don't really get", "offended and I find that", "absolutely offensive."],
  ["This is what a consumer", "revolt with power looks", "like."],
  ["Our opposition is corrupt.", "They are liars.", "They are privileged."],
  ["Reddit admins are trying", "to 'gentrify' this", "website's userbase."],
  ["I hate you all so much", "with every fiber in my", "body."],  
  ["As a person who's", "practically a feminist,", "fuck that bitch."],
  ["That's not child porn,", "at least not in the US.", ""],
  ["I sexually identify", "as an attack helicopter.", ""],
  ["Even the POTUS is an SJW", "with campus rape stats", "and the wage gap myth."],
  ["All you do is ban", "'offensive' subreddits by", "crying to admins."], 
  ["This is pretty much the", "reason why women should", "not be able to vote."],
  ["I can't think of a word", "that's more sexually", "oppressive than 'creepy'."],
  ["Men care much more about", "womens' issues than", "women care about mens'."],
  ["We don't need the media", "shoving women scientists", "down our throats."],
  ["SRS is just SJWs trying to", "make reddit comform to", "their stupid cult beliefs."],
  ["The SRS cabal controls", "too much of and is", "ruining Reddit."],
  ["The modern feminist", "movement looks", "something more like ISIS."],
  ["This is why black America", "has not progressed in", "the 60 years since MLK."],
  ["Die starving and", "desperate in your ivory", "tower, SJW shitlords."],
  ["There seems to be a", "feminism tone-police", "take over."],
  ["The entire ideal you are", "trying to enforce is", "just communistic."],
  ["It just so happens that", "certain races have more", "subcultures that I hate."],
  ["There are thousands of", "pedophiles on Reddit. Most", "of us are good people."],
  ["Lying about rape should", "be a greater offense", "than rape."],
  ["Honestly, this just kinda", "shows why racism is", "still a thing."],
  ["You are supporting", "some of the vilest", "imaginable extremism."]  
];
